version: 2

updates:
  - package-ecosystem: pip
    directory: "/conformance/stable/sigstore-python"
    schedule:
      interval: daily
    labels:
      - "dependencies"
      - "matrix:stable"

  - package-ecosystem: docker
    directory: "/conformance/stable/cosign"
    schedule:
      interval: daily
    registries:
      - gcr-sigstore
    allow:
      - dependency-name: cosign
    labels:
      - "dependencies"
      - "matrix:stable"

  - package-ecosystem: gitsubmodule
    directory: "/conformance/nightly/cosign"
    schedule:
      interval: daily
    labels:
      - "dependencies"
      - "matrix:nightly"

  - package-ecosystem: gitsubmodule
    directory: "/conformance/nightly/sigstore-python"
    schedule:
      interval: daily
    labels:
      - "dependencies"
      - "matrix:nightly"

registries:
  gcr-sigstore:
    type: docker-registry
    url: https://gcr.io/projectsigstore
